config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :teams do
    resources :comments
  end
  resources :users do
    resources :bios
    resources :stats
    member do
      put "like", to: "users#upvote"
      put "dislike", to: "users#downvote"
    end
  end

  root 'welcome#index'

  if Rails.env.development?
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_votable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  # mount_uploader :profile_photo, ProfilePhotoUploader

  validates :username, presence: true, uniqueness: true
  validates :summoner_name, presence: true, uniqueness: true
  validates :primary_role, presence: true
  validates :secondary_role, presence: true

  # belongs_to :team
  has_many :teams
  has_many :comments
  has_many :votes
  has_many :bios
  has_one  :stat

  def admin?
    admin == true
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_filter :require_no_authentication, only: [ :new, :create, :cancel ]
  prepend_before_filter :authenticate_scope!, only: [:edit, :update, :destroy]

  # GET /resource/sign_up
  def new
    build_resource({})
    @validatable = devise_mapping.validatable?
    if @validatable
      @minimum_password_length = resource_class.password_length.min
    end
    yield resource if block_given?
    respond_with self.resource
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
    resource_saved = resource.save
    yield resource if block_given?

    if resource_saved
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        ### Create Stat for new user; @user now exists as current_user ###
        @stat = Stat.new
        @stat.user = @user
        @stat.save!
        StatsUpdateWorker.perform_async(@user.summoner_name, @stat.id)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      @validatable = devise_mapping.validatable?
      if @validatable
        @minimum_password_length = resource_class.password_length.min
      end
      respond_with resource
    end

  end

  # GET /resource/edit
  def edit
    render :edit
  end

  # PUT /resource
  # We need to use a copy of the resource because we don't want to change
  # the current user in place.
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
        :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      sign_in resource_name, resource, bypass: true
      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # DELETE /resource
  def destroy
    resource.destroy
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_flashing_format?
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    expire_data_after_sign_in!
    redirect_to new_registration_path(resource_name)
  end

  protected

  def update_needs_confirmation?(resource, previous)
    resource.respond_to?(:pending_reconfirmation?) &&
    resource.pending_reconfirmation? &&
    previous != resource.unconfirmed_email
  end

  # By default we want to require a password checks on update.
  # You can overwrite this method in your own RegistrationsController.
  def update_resource(resource, params)
    resource.update_with_password(params)
  end

  # Build a devise resource passing in the session. Useful to move
  # temporary session data to the newly created user.
  def build_resource(hash=nil)
    self.resource = resource_class.new_with_session(hash || {}, session)
  end

  # Signs in a user on sign up. You can overwrite this method in your own
  # RegistrationsController.
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end

  # The path used after sign up. You need to overwrite this method
  # in your own RegistrationsController.
  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

  # The path used after sign up for inactive accounts. You need to overwrite
  # this method in your own RegistrationsController.
  def after_inactive_sign_up_path_for(resource)
    scope = Devise::Mapping.find_scope!(resource)
    router_name = Devise.mappings[scope].router_name
    context = router_name ? send(router_name) : self
    context.respond_to?(:root_path) ? context.root_path : "/"
  end

  # The default url to be used after updating a resource. You need to overwrite
  # this method in your own RegistrationsController.
  def after_update_path_for(resource)
    signed_in_root_path(resource)
  end

  # Authenticates the current scope and gets the current resource from the session.
  def authenticate_scope!
    send(:"authenticate_#{resource_name}!", force: true)
    self.resource = send(:"current_#{resource_name}")
  end

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end

  def account_update_params
    devise_parameter_sanitizer.sanitize(:account_update)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, only: [:upvote, :downvote]
  before_action :get_user, except: [:index]

  def index
  end

  def show
    @stat  = Stat.new
    @stats = @user.stat
    @bios  = @user.bios
    @bio   = Bio.new
    @user_teams = Team.all.where(:user_id => @user.id)
    @likes    = @user.get_likes.size
    @dislikes = @user.get_dislikes.size
    @percentage_likes=
    if @likes > 0
      sprintf('%.0f', ((@likes.to_f / (@likes.to_f + @dislikes.to_f)) * 100)).to_s + '%'
    elsif @likes == 0 && @dislikes == 0
      "No registered votes"
    elsif @likes == 0 && @dislikes > 0
      "Uh-oh, better change your behavior!"
    else
      "100%"
    end
  end

  def update

    if @user.update(user_params)
      flash[:success] = "You have successfully updated your profile."
      redirect_to user_path(@user)
    else
      render 'show'
    end
  end

  def upvote
    @user.vote_by voter: current_user, vote: 'like'
    redirect_to @user
  end

  def downvote
    @user.vote_by voter: current_user, vote: 'bad'
    redirect_to @user
  end


  private

  def user_params
    return { email: nil } unless params[:user]
    params.require(:user).permit(:email)
  end

  def get_user
    @user = User.find(params[:id])
  end

end

app/views/users/_create_stats.html.erb
<!-- Form for new_stat -->
<%= form_for [@user, @stat], remote: true do |f| %>
  <% if @stat.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@stat.errors.count, "error") %>
      prohibited these stats from being saved:
    </h2>
    <ul>
      <% @stat.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <p id="stats-box">
    <%= f.hidden_field :summoner_id %>
    <%= f.hidden_field :lolking_profile_url %>
    <%= f.hidden_field :tier %>
  </p>

  <div id="create-stats-button">
    <%= f.submit 'Create Stats', class: "button", id: "create-stats" %>
  </div>
<% end %>

app/views/users/_stats.html.erb
<ul class="panel callout radius">
  <li class="rank">
    <% if @stats.present? %>
    Rank:
    <tag class="info-for-vcard"><%= "#{@stats.tier}" %></tag>
    <% end %>
  </li>
  <li class="primary_role">
    Primary Role:
    <tag class="info-for-vcard"><%= "#{@user.primary_role.capitalize}" %></tag>
  </li>
  <li class="secondary_role">
    Secondary Role:
    <tag class="info-for-vcard"><%= "#{@user.secondary_role.capitalize}" %></tag>
  </li>
  <li class="lolking_profile_link">
    <% if @stats.present? %>
    <u><%= link_to "LoLKing Profile", @stats.lolking_profile_url %></u>
    <% end %>
  </li>
  <% if @user == current_user %>
  <li class="email">
    Email:
    <tag class="info-for-vcard"><%= "#{@user.email}" %></tag>
  </li>
  <% end %>
</ul>

app/views/users/_update_stats.html.erb
<%= form_for [@user, @stats] do |f| %>
  <%= f.hidden_field :tier %>
  <%= f.submit "Update", class: "button", id: "update-stats-button" %>
<% end %>

app/views/users/show.html.erb
<div class="user-show">
  <span style="color: rgba(0,0,0,0)">.</span>
  <div class="row information">

    <h1 id="user-show-header"><%= "#{@user.summoner_name}'s Profile" %></h1><br/>

    <aside class="large-4 columns user-sidebar">

      <!-- Displays stats box -->
      <div id="stat-results">
        <% if @stats && @stats.tier != "" %>
        <%= render "stats" %>
        <% end %>
      </div>

      <% if @bio %>
      <% @bios.each do |bio| %>
      <ul class="panel callout radius">
        Bio:
        <tag class="info-for-vcard"><%= bio.body %></tag>
      </ul>
      <div id="edit-delete-bio-buttons">
        <% if @user == current_user %>
        <%= link_to 'Edit', edit_user_bio_path(@user, bio),
                class: "button tiny edit",
                id: "update-bio-button" %>
        <%= link_to 'Delete', user_bio_path(@user, bio),
                method: :delete,
                data: {confirm: 'Are you sure you want to delete bio?'},
                class: "button tiny delete",
                id: "delete-bio-button" %>
        <% end %>
      </div>
      <% end %>

      <% if current_user == @user && @bios.count < 1 %>
      <%= form_for [@user, @bio] do |f| %>
      <% if @bio.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@bio.errors.count, "error") %>
          prohibited this bio from being saved:</h2>
        <ul>
          <% @bio.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <p>
        <%= f.label :body, class: 'label' %><br>
        <%= f.text_area :body, rows: '10' %>
      </p>

      <%= f.submit 'Add Bio', class: "button tiny" %>
      <% end %>
      <% end %>
      <% end %>
    </aside>

    <% if @stats.nil? %>
      <%= render "create_stats" %>
    <% elsif @stats.present? %>
      <%= render "update_stats" %>
    <% end %>
    <hr>

    <div id="like-dislike-buttons">
      <% if current_user != @user %>
      <%= link_to 'Like', like_user_path,
    method: :put, class: "upvote button success tiny" %>

      <%= link_to 'Dislike', dislike_user_path,
    method: :put, class: "downvote button alert tiny" %><br>
      <% end %>
    </div>

    <div class="vote-score">
      <tag class="likes"><%= "#{@likes} Upvotes / " %></tag>
      <tag class="dislikes"><%= "#{@dislikes} Downvotes" %></tag>
      <%= " - #{@percentage_likes}" %>
    </div>

    <h3 id="user-teams-header"><%= "#{@user.summoner_name}'s Teams" %></h3>
    <ul id="user-teams-list">
      <% @user_teams.each do |team| %>
      <div class="panel radius">
        <li><%# link_to "#{team.user.stat.tier}", team_path(team) %><br>
          Created by:
          <%= "#{team.user.summoner_name}" %><br>
          <%= "  #{team[:about]}" %></li>
      </div>
      <% end %>
    </ul>

  </div>
</div>

app/views/users/show.js.erb
$("#stat-results").update("<%= j (render 'stats') %>")
$("#new-stats").html("<%= j (render 'create_stats') %>");
$("#update-stats").html("<%= j (render 'update_stats') %>");