config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :teams do
    resources :comments
  end
  resources :users do
    resources :bios
    resources :stats
    member do
      put "like", to: "users#upvote"
      put "dislike", to: "users#downvote"
    end
  end

  root 'welcome#index'

  if Rails.env.development?
    mount Sidekiq::Web, at: "/sidekiq"
  end
end

app/views/layouts/_nav.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'LoLTeamBuilder', root_path, class: "logo" %> </h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <% if current_user %>
        <li><%= link_to "Welcome back #{current_user.username}!",
          user_path(current_user),
          class: "button notice",
          id: "welcome-back-button" %></li>
      <% end %>
      <li><%= link_to "Home", root_path, class: "btn success" %></li>
      <li><%= link_to 'Find Team', teams_path %> </li>

      <% if current_user %>
        <li class="has-dropdown">
          <%= link_to "Profile", user_path(current_user), class: "btn success" %>
          <ul class="dropdown">
            <li><%= link_to "Update", edit_user_registration_path(current_user), class: "btn success" %></li>
          </ul>
        </li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn success" %></li>

      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path, class: "btn success" %></li>
        <li><%= link_to "Log In", new_user_session_path, class: "btn success" %></li>
      <% end %>
    </ul>
  </section>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="container">
      <%= render 'layouts/nav' %>

      <% flash.each do |name, msg| %>
        <div class="alert-box <%= name %>">
          <%= msg %>
        </div>
      <% end %>

      <%= yield %>

    </div>

    <%= javascript_include_tag "jquery","application" %>
    <script src="/js/vendor/jquery.js"></script>
    <script src="/js/vendor/fastclick.js"></script>
    <script src="/js/foundation.min.js"></script>
    <script>
      $(document).foundation();
    </script>

  </body>
</html>